### PR TITLE
chore: export `ConfigurationResult` for reusing

### PR DESCRIPTION
**Pull request by JounQin**
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

related https://github.com/mdx-js/eslint-mdx/pull/486/files/88932f183ddbe6f033a794d921fac08427a58ef5#diff-6c1bdf004fec1432e8c27da2092dbb688eccbf3693501fe64a28ab0e3ec4aa28

### CODE REVIEW

**Comment by JounQin** [comment]
image

Weird, I don't think it's related to this PR.

**Comment by fisker** [comment]
Bug in lilconfig, already fixed, https://github.com/antonk52/lilconfig/blob/8deeb3b8e4c4f073e329b29a53781d4f8fc79183/src/index.ts#L217

**Comment by fisker** [comment]
You can add `test/fixtures/malformed-package-file/*` to `.prettierignore`

**Comment by JounQin** [comment]
> You can add `test/fixtures/malformed-package-file/*` to `.prettierignore`

I don't think that's what we want, I'm locking `prettier@~3.0.0` temporarily.

**Comment by wooorm** [comment]
Thanks!

I added docs, use `ConfigResult` instead (we also have `ConfigTransform` already), and I did update the `.prettierignore` to solve the crash!

**Comment by wooorm** [comment]
Thanks, [released](https://github.com/unifiedjs/unified-engine/releases/tag/11.2.0)!

**Pull request closed without merging**
